# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Load Google Service file
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $DATA | base64 -di > android/app/google-services.json
    - name: Write build number
      env:
        DATA: v1.0.0-${{ github.run_number }}
      run: echo $DATA  > assets/data/release-number.txt
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.3.5'
        channel: 'stable' # or: 'beta' or 'dev'
    - run: flutter pub get
    - run: flutter build apk
    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v3
      with:
        name: release-apk.apk
        path: build/app/outputs/apk/release/app-release.apk
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/release/*"
        tag: v1.0.0-${{ github.run_number }}
